import {ArrowRight, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, Loader2, Mail, MessageSquare, Moon, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, Sun, Trash, User, X, Workflow, Bike, Car, CloudOff, BatteryCharging, Package, MapPin, Flag, Terminal, Info, Lightbulb, LayoutGrid, Manual} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  bike: Bike,
  car: Car,
  cloudOff: CloudOff,
  batteryCharging: BatteryCharging,
  package: Package,
  mapPin: MapPin,
  flag: Flag,
  terminal: Terminal,
  info: Info,
  lightbulb: Lightbulb,
  layoutGrid: LayoutGrid,
  manual: Manual,
};

export {Icons};
